FROM golang:1.17-alpine

WORKDIR /go/src/github.com/nao-18/golang-tdd-app-with-tdd-book
COPY ./src .

RUN apk upgrade --update && \
  apk --no-cache add git

# RUN go get -u github.com/cosmtrek/air && \
#   go build -o /go/bin/air github.com/cosmtrek/air

# CMD ["air", "-c", ".air.toml"]