version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/dockerfile
    volumes:
      - ./src:/go/src/github.com/nao-18/golang-tdd-app-with-tdd-book
    tty: true
